languagedirection: rtl
Menus:
  main:
    - identifier: blog
      name: مدونتي
      title: مقالات المدونة
params:
  description: هذا هو الموقع الشخصي لزكرياء إبڨازن، تجدون فيه سيرتي الذاتية، تجاربي، مشاريعي، مدونتي وأوراقي البحثية
  hero:
    enable: true
    intro: "السلام عليكم، اسمي"
    title: "زكرياء."
    subtitle: "مهندس وعالم بيانات متخصص في الذكاء الاصطناعي"
    image: /images/zakaria_mountain.jpg
    button:
      enable: true
      name: "سيرة ذاتية"
      url: "/assets/ZAKARIA_YBEGGAZENE_RESUME_DATA.pdf"
      download: true
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/zakaria-ybeggazene
        - icon: fab fa-github
          url: https://github.com/zakaria-ybeggazene
        - icon: fab fa-twitter
          url: https://twitter.com/zakaria_ygz
about:
  enable: true
  title: "عَنِّي"
  content: |-
    أنا عالم بيانات مختص في الذكاء الاصطناعي. لدي خلفية في علوم الكمبوتر والرياضيات. أعمل حاليا كعالم بيانات متمرن لدى [Dassault Systèmes SE](https://www.3ds.com/) بضواحي باريس في فرنسا.

    أعمل حاليا على مشروع يساعد المطورين على تصحيح الأخطاء البرمجية بشكل تلقائي باستعمال الذكاء الاصطناعي (نماذج اللغة الكبيرة)
  skills:
    enable: true
    title: "هذه بعض التكنولوجيات التي استعملتها مؤخرا"
    items:
      - "Python"
      - "Tensorflow"
      - "Keras"
      - "PyTorch"
      - "HuggingFace"
      - "Google Cloud Platform"

# Experience
experience:
  enable: true
  title: "تجاربي المهنية"
  items:
    - job: "Data Scientist Apprentice"
      company: "Dassault Systèmes SE"
      companyUrl: "https://www.3ds.com/"
      date: "August 2021 - present"
      # featuredLink:
      #   enable: true
      #   name: "View the project"
      #   url: "https://example.com"
      content: | 
        I am currently working on a R&D project that aims to help developers correct their code bugs automatically with AI (Large Language Models).
        My missions are:
        - State of the art study on automatic code correction (using Deep Learning approaches)
        - Implementation of pipelines for massive data collection (Spark, HDFS, Hive ...)
        - Data exploration, analysis and pre-processing (e.g. change of representation using abstract syntax trees ...)
        - Development of machine learning models capable of proposing corrections (Seq2Seq, Graph Neural Networks, Transformers: GPT, BERT, T5 ...)
        - Evaluation, comparison and characterization of the models through tests performed on real production data
        - Integration of the models in our production DevOps chains (Web Service for IDE plugin)
        - Communication and presentation of the results in an innovative way for the customers

    - job: "Image Analysis and Statistical Support Intern"
      company: "Enza Zaden France"
      companyUrl: "https://www.enzazaden.com/fr"
      date: "May 2021 - August 2021"
      # featuredLink:
      #   enable: true
      #   url: "https://example.com"
      info:
        enable: true
        content: 3 months internship (remote)
      content: |
        Enza Zaden is an international, multicultural vegetable seed breeding company that increasingly supports breeding with artificial intelligence (AI).
        Internship's main missions:
        - Image analysis by segmentation and creation of the statistical report in R.
        - Application of ML algorithms on the information extracted for prediction.
        - Optimization of execution times and deployment of the solution on the cloud (Azure).

# Education
education:
  enable: true
  title: "تعليم"
  index: false
  items:
    - title: "Master of Artificial Intelligence, Systems, Data (Apprenticeship track)"
      school:
        name: "University of Paris Dauphine - PSL, Paris"
        url: "https://dauphine.psl.eu/en/training/masters-degrees/computer-science/m2-artificial-intelligence-systems-data"
      date: "2022 - 2023"
      content: |-
        Extracurricular Activities
          - Membership in the master's association "Association des étudiants du master IASD"
          - Participation in tech events such as [VivaTechnology 2023](https://vivatechnology.com/)
    - title: "Master of Data Science (Apprenticeship track)"
      school:
        name: "University of Paris Saclay, Orsay"
        url: "https://www.universite-paris-saclay.fr/en/education/master/computer-science/m1-data-science-alternance"
      date: "2021 - 2022"
      # content: |-
      #   I Publiced two papers in the ACM SIGCHI Conference on Artificial Intelligence.
      #   - [Fast and Accurate Object Detection with a Single Convolutional Neural Network](https://example.com)
      #   - Face mask detection using a single convolutional neural network.

      #   Extracurricular Activities
      #     - Lorem ipsum dolor sit amet consectetur adipisicing elit. 
      #     - Tempora esse, eaque delectus nulla quo doloribus itaque expedita alias natus optio totam maxime nihil excepturi velit a animi laborum hic similique.
      # featuredLink:
      #   enable: true
      #   name: "My academic record"
      #   url: "https://example.com"
    - title: "Computer Science and Mathematics for Decision-Making and Data Bachelor's Year 3"
      school:
        name: "University of Paris Dauphine - PSL, Paris"
        url: "https://dauphine.psl.eu/en/training/bachelors-degrees/bachelors-degree-in-organizational-computer-science/bachelors-year-3-decision-support-it-and-mathematics"
      date: "2020 - 2021"
    - title: "Preparatory Cycle in Computer Science (Bac +2)"
      school:
        name: "ESI (Ecole Nationale supérieure d'Informatique), Algiers"
        url: "https://www.esi.dz/wp-content/uploads/2021/01/ESI_CPI_Programmes_Janvier_2012.pdf"
      date: "2018 - 2020"

#Contact
contact:
  enable: true
  title: "تواصل معي"
  content: بريدي الإلكتروني دائما مفتوح. إذا أردت أن تسألني سؤالا أو أن تلقي التحية فقط، سأحاول الرد بكل سرورِ
  email: zakariaybeggazene@gmail.com
  btnName: ابعث إيميل
  # formspree:
  #   enable: true # `contact.email` value will be ignored
  #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
  #   emailCaption: "Enter your email address"
  #   messageCaption: "Enter your message here"

weight: 2